# defaults/main.yml

snippets_path: "/var/lib/vz/snippets"
vm_storage_pool: "vmpool"
tmp_min_free_gb: 5
storage_min_free_gb: 10
cleanup_downloaded_images: false
recreate_templates: false

vm_defaults:
  memory: 1024
  cores: 1
  disk_size: "12G"
  network_bridge: "vmbr0"
  cpu_type: "host"
  ostype: "l26"
  machine: "q35"
  bios: "seabios"
  scsihw: "virtio-scsi-pci"
  agent: "enabled=1"

os_templates:
  ubuntu24:
    template_id: 3000
    vm_name: "ubuntu-24-04-template"
    image_url: "https://mirror.yandex.ru/ubuntu-cloud-images/noble/current/noble-server-cloudimg-amd64.img"
    image_filename: "noble-server-cloudimg-amd64.img"
    enabled: true
    cloud_init_template: ubuntu24

  ubuntu26:
    template_id: 3004
    vm_name: "ubuntu-26-04-template"
    image_url: "https://mirror.yandex.ru/ubuntu-cloud-images/resolute/current/resolute-server-cloudimg-amd64.img"
    image_filename: "resolute-server-cloudimg-amd64.img"
    enabled: true
    cloud_init_template: ubuntu26

  almalinux:
    template_id: 3001
    vm_name: "almalinux-9-template"
    image_url: "https://mirror.yandex.ru/almalinux/9.7/cloud/x86_64/images/AlmaLinux-9-GenericCloud-9.7-20251118.x86_64.qcow2"
    image_filename: "AlmaLinux-9-GenericCloud-9.7-20251118.x86_64.qcow2"
    enabled: true
    cloud_init_template: almalinux

  fedora:
    template_id: 3002
    vm_name: "fedora-43-template"
    image_url: "https://mirror.yandex.ru/fedora/linux/releases/43/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2"
    image_filename: "Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2"
    enabled: true
    cloud_init_template: fedora
