---
- name: Create Proxmox Templates from Cloud Images
  hosts: proxmox
  serial: 1
  vars:
    cleanup_downloaded_images: false

  tasks:
    - name: Create Templates
      ansible.builtin.include_role:
        name: opscores.proxmox_vm.create_templates
