---
- name: Create Proxmox Templates from Cloud Images
  hosts: proxmox
  serial: 1
  vars:
    cleanup_downloaded_images: false

  collections:
    - opscores.proxmox_vm

  tasks:
    - name: Create Templates
      include_role:
        name: create_templates
